### ISSUE TITLE
QT Framework Research

### ISSUE THREAD

**Issue by luis-ffe** [SEAME-pt/Team02-WarmUp#39]
## Description

- research
- use ide and test it
- see how to use automation
- do tuturials

**Comment by mjorgecruz** [comment]
## Description of main points

- We have been using QT framework for a few days. Configuration was made so that we could still use our usual IDE (VS Code) making use of all the features that Qt offers.
- Implemented UI for both ex03 and ex04, using Qt Widget Design.
- Grasped all base features, and we are all more comfortable using Qt at this point.
